##
# Sonarr - TV show search and retrieval service https://sonarr.tv/
# Docker Hub: https://hub.docker.com/r/linuxserver/sonarr
# Wiki: https://wiki.servarr.com/
##  
services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    depends_on: 
      - nginx-proxy-manager
      - sabnzbd
      - qbittorrent
    network_mode: 'host' # Use host networking for better performance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${APP_CONFIG}/sonarr:/config         # Moved outside of docker for portability
      - ${APP_BACKUP}/sonarr:/config/Backups # Saves backups to external filesystem for recovery
      - ${PLEX_MEDIA}:/data                  # Common root directory for plex, qBittorrent, sabnzbd, radarr, and sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
