##
# Atlas UI - Scans, analyzes, and visualizes network infrastructure
# Gihub: https://github.com/karam-ajaj/atlas
# UI: http://<host-ip>:8888  API: http://<host-ip>:8889
##
services:
  atlas:
    container_name: atlas
    image: keinstien/atlas:latest
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - ATLAS_UI_PORT=8888
      - ATLAS_API_PORT=8889
      - FASTSCAN_INTERVAL=60
      - DOCKERSCAN_INTERVAL=60
      - DEEPSCAN_INTERVAL=300
      - SUBNETS=192.168.86.0/24,172.18.0.0/16
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
