##
# My Plex services stack
##

name: plex-ecosystem

include:
  - sabnzbd.yml             # Usenet downloader
  - qbittorrent.yml         # Torrent downloader
  - notifiarr.yml           # Server notification service
  - prowlarr.yml            # Torrent and Usenet indexer management
  - sonarr.yml              # TV show download automation
  - radarr.yml              # Movie download automation
  - seerr.yml               # Media discovery and request service
  - plex/compose.yml        # Plex media server
  - plex-music-ratings-sync.yml # Sync ratings between Plex and music files
  - tautulli.yml               # Plex usage monitoring
  - tdarr.yml                  # Automated media transcoding
  - cloudflare-ddns.yml         # Keeps request.blacktower.com's A record current

# Disabled services
#  - profilarr.yml           # Quality profile management for Radarr and Sonarr
