##
# Nginx Proxy Manager - Reverse proxy server https://nginxproxymanager.com/guide/
##
name: nginx-proxy-manager
services:
  nginx-proxy-manager:
    container_name: 'nginx-proxy-manager'
    image: 'jc21/nginx-proxy-manager:latest'
#    network_mode: 'host' # Use host networking for better performance
    restart: unless-stopped  
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${HOST_MOUNT}/config/nginx-proxy-manager/data:/data
      - ${HOST_MOUNT}/config/nginx-proxy-manager/etc/letsencrypt:/etc/letsencrypt
    networks:
      - proxied

networks:
  proxied:
    name: proxied
