##
# Plex Music Ratings Sync - Sync ratings between Plex and music file metadata
# GitHub: https://github.com/rfgamaral/plex-music-ratings-sync
##
services:
  plex-music-ratings-sync:
    image: ghcr.io/rfgamaral/plex-music-ratings-sync
    container_name: plex-music-ratings-sync
    command: sync
    restart: on-failure:2
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      plex:
        condition: service_healthy
    volumes:
      - ${HOST_MOUNT}/config/plex-music-ratings-sync:/app/data
      - ${HOST_MOUNT}/data/media/music:/data/media/music

  ofelia-scheduler:
    image: mcuadros/ofelia
    container_name: ofelia-scheduler
    network_mode: host
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plex-music-ratings-sync.schedule: '@every 1d'
      ofelia.job-run.plex-music-ratings-sync.container: 'plex-music-ratings-sync'
