services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"   # Portainer UI (HTTP)
      - "9443:9443"   # Portainer UI (HTTPS)
      - "8001:8000"   # Edge/agent communications
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_CONFIG}/portainer:/data # Moved outside of docker for portability
#    networks:
#      - a_network

#networks:
#  a_network:
#    name: portainer_network

#  agent:
#    image: portainer/agent:latest
#    container_name: portainer_agent
#    restart: unless-stopped
#    environment:
#      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
#    ports:
#      - "9001:9001"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /var/lib/docker/volumes:/var/lib/docker/volumes
