##
# qBittorrent - Torrent download service https://www.qbittorrent.org/
# Docker Hub: https://hub.docker.com/r/linuxserver/qbittorrent
##  
services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest

#    network_mode: 'host' # Use host networking for better performance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8282 # Changed from the default 8080 to not conflict with sabnzbd
      - TORRENTING_PORT=6881
    volumes:
      - ${HOST_MOUNT}/config/qbittorrent:/config
      - ${HOST_MOUNT}/data/torrents:/data/torrents
    ports:
      - 8282:8282 # Changed from the default 8080 to not conflict with sabnzbd
      - 6881:6881
      - 6881:6881/udp
    healthcheck:
      test: curl -sf http://localhost:8282 || exit 1
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - media
      - proxied

networks:
  media:
  proxied:
    external: true
    name: proxied

