##
# Radarr - Movie search and retrieval service https://radarr.video/
# Docker Hub: https://hub.docker.com/r/linuxserver/radarr
# Wiki: https://wiki.servarr.com/
##
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on: 
      - nginx-proxy-manager
      - qbittorrent
      - sabnzbd
#      - profilarr
#    network_mode: 'host' # Use host networking for better performance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${HOST_MOUNT}/config/radarr:/config
      - ${HOST_MOUNT}/backups/radarr:/config/Backups
      - ${HOST_MOUNT}/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - proxied
      - media

networks:
  proxied:
    external: true
  media:
    external: true
