##
# Radarr - Movie search and retrieval service https://radarr.video/
# Docker Hub: https://hub.docker.com/r/linuxserver/radarr
# Wiki: https://wiki.servarr.com/
##
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      qbittorrent:
        condition: service_healthy
      sabnzbd:
        condition: service_healthy
#      profilarr:
#        condition: service_started
#    network_mode: 'host' # Use host networking for better performance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${HOST_MOUNT}/config/radarr:/config
      - ${HOST_MOUNT}/backups/radarr:/config/Backups
      - ${HOST_MOUNT}/data:/data
    healthcheck:
      test: curl -sf http://localhost:7878/ping || exit 1
      start_period: 30s
      interval: 15s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - media
      - proxied

networks:
  media:
  proxied:
    external: true
    name: proxied

