##
# Readarr - Docker image maintainer https://hotio.dev/containers/readarr
##
name: readarr
services:
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    network_mode: 'host' # Use host networking for better performance
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - ${APP_CONFIG}/readarr:/config         # Moved outside of docker for portability
      - ${APP_BACKUP}/readarr:/config/Backups # Saves backups to external filesystem for recovery
      - ${PLEX_MEDIA}:/data                   # Media root
