##
# Readarr - Docker image maintainer https://hotio.dev/containers/readarr
##
name: readarr
services:
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
#      - /<host_folder_config>:/config
#      - /<host_folder_data>:/data
      - ${PLEX_ROOT}/config/readarr:/config   # Moved outside of docker for portability
      - ${PLEX_ROOT}/backups:/config/Backups  # Saves backups to external filesystem for recovery
      - ${PLEX_MEDIA}:/data                   # Media root
