##
# Prowlarr - Torrent and Usenet indexing service https://prowlarr.com/
# Docker Hub: https://hub.docker.com/r/linuxserver/prowlarr
#
# Note: Restore from backup after recreating the container
##  
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - prowlarr:/config                      # Using docker volumes as configurations can be restored from backup
      - ${PLEX_ROOT}/backups:/config/Backups  # Saves backups to external filesystem for recovery
    ports:
      - 9696:9696
    restart: unless-stopped   
volumes:
  prowlarr: