##
# Apprise - Notification service https://github.com/caronc/apprise
# Docker Hub: https://hub.docker.com/r/caronc/apprise
# Apprise URL format: apprise://host.docker.internal:8000/token?tags=<tag> | https://github.com/caronc/apprise/wiki/CLI_Usage
##  
name: 'apprise'
services:
  apprise:
    container_name: 'apprise'
    image: 'lscr.io/linuxserver/apprise-api:latest' # Use LinuxServer.io's version for better support
    network_mode: 'host' # Use host networking for better performance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${APP_CONFIG}/apprise:/config # Moved outside of docker for portability
      - ${APP_CONFIG}/apprise:/plugin # Moved outside of docker for portability
      - ${APP_CONFIG}/apprise:/attach # Moved outside of docker for portability
    ports:
      - 8000:8000
    restart: unless-stopped
