##
# Plex - Media sharing service https://plex.tv
# Docker Hub: https://hub.docker.com/r/plexinc/pms-docker
##
services:
  plex:
    build:
      context: .
      dockerfile: dockerfile
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=America/Los_Angeles
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
    volumes:
      - ${APP_CONFIG}/plex:/config        # Moved outside of docker for portability
      - ${PLEX_MEDIA}:/data               # Media root
      - ${PLEX_TRANSCODE_TEMP}:/transcode # Transcode temp
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp 
      - 32412:32412/udp 
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
#volumes:
#  plex:
