##
# Plex - Media sharing service https://plex.tv
# Docker Hub: https://hub.docker.com/r/plexinc/pms-docker
##
services:
  plex:
    build:
      context: .
      dockerfile: dockerfile
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=America/Los_Angeles
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
    volumes:
      - ${HOST_MOUNT}/config/plex:/config
      - ${HOST_MOUNT}/data:/data
      - ${HOST_MOUNT}/plex-transcode-temp:/transcode
    healthcheck:
      test: curl -sf http://localhost:32400/identity || exit 1
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped