FROM plexinc/pms-docker:latest
WORKDIR /tmp

# Update package list and install Git
RUN apt-get update && apt-get install -y git && apt-get clean

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
