FROM plexinc/pms-docker:latest

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY audnexus-init.sh /etc/cont-init.d/99-audnexus
RUN chmod +x /etc/cont-init.d/99-audnexus
