##
# Radarr - Movie search and retrieval service https://radarr.video/
# Docker Hub: https://hub.docker.com/r/linuxserver/radarr
# Wiki: https://wiki.servarr.com/
##
services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on: 
      - nginx-proxy-manager
      - qbittorrent
      - sabnzbd
    network_mode: 'host' # Use host networking for better performance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${APP_CONFIG}/radarr:/config         # Moved outside of docker for portability
      - ${APP_BACKUP}/radarr:/config/Backups # Saves backups to external filesystem for recovery
      - ${PLEX_MEDIA}:/data                  # Common root directory for plex, qBittorrent, sabnzbd, radarr, and sonarr
    ports:
      - 7878:7878
    restart: unless-stopped
