##
# Watchtower - Docker image maintainer https://containrrr.dev/watchtower/
##
name: watchtower
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    network_mode: "host" # Use host networking for better performance
    environment:
      - WATCHTOWER_CLEANUP=true      # Remove old images after update
      - WATCHTOWER_POLL_INTERVAL=600 # seconds
      - WATCHTOWER_DEBUG=false       # Enable debug logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 # seconds 