##
# Watchtower - Docker image maintainer https://containrrr.dev/watchtower/
##
name: watchtower
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 30 # seconds (default is once / day) 