##
# Nginx Proxy Manager - Reverse proxy server https://nginxproxymanager.com/guide/
##
name: nginx-proxy-manager
services:
  nginx-proxy-manager:
    container_name: 'proxy'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped  
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - data:/etc/letsencrypt
volumes:
    data: