##
# Nginx Proxy Manager - Reverse proxy server https://nginxproxymanager.com/guide/
##
name: nginx-proxy-manager
services:
  nginx-proxy-manager:
    container_name: 'nginx-proxy-manager'
    image: 'jc21/nginx-proxy-manager:latest'
    network_mode: 'host' # Use host networking for better performance
    restart: unless-stopped  
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${APP_CONFIG}/nginx-proxy-manager/data:/data                       # Moved outside of docker for portability
      - ${APP_CONFIG}/nginx-proxy-manager/etc/letsencrypt:/etc/letsencrypt # Moved outside of docker for portability
