##
# Nginx Proxy Manager - Reverse proxy server https://nginxproxymanager.com/guide/
##
name: nginx-proxy-manager
services:
  nginx-proxy-manager:
    container_name: 'proxy'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped  
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${PLEX_ROOT}/config/nginx-proxy-manager/data:/data # Moved outside of docker for portability
      - ${PLEX_ROOT}/config/nginx-proxy-manager/etc/letsencrypt:/etc/letsencrypt # Moved outside of docker for portability
