##
# Notifiarr - Client of Notifiarr.com notification service https://notifiarr.com/
# Docker Hub: https://hub.docker.com/r/golift/notifiarr
##  
name: notifiarr
services:
  notifiarr:
    container_name: notifiarr
    image: golift/notifiarr
    hostname: notifiarr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - DN_API_KEY=3ef0d9c1-4fc0-4e89-994b-c23abc303419
    volumes:
      - notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    ports:
      - 5454:5454
volumes:
  notifiarr:
      
